[package]
name = "memorize-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6"
tokio = { version = "1", features = ["rt", "time", "sync", "macros"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
